### ISSUE TITLE
Restore git credentials fail

### ISSUE THREAD

**Issue by yarons** [peter-evans/autopep8#64]
https://github.com/Maagan-Michael/invitease/runs/6257049794?check_suite_focus=true

This is the from the logs:
```
Restore persisted git credentials
  /usr/bin/git config --local --name-only --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
  http.https://github.com/.extraheader
  /usr/bin/git config --local --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
  http.https://github.com/.extraheader AUTHORIZATION: basic ***
  /usr/bin/git config --local --unset http.https://github.com/.extraheader ^AUTHORIZATION:
  Unset config key 'http.https://github.com/.extraheader'
  /usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
  Persisted git credentials restored
```

**Comment by peter-evans** [comment]
Hi @yarons 

The error is in the step before that:
![image](https://user-images.githubusercontent.com/18365890/166403633-38db0830-933b-4cd5-94e9-acec14059618.png)

You are trying to request a review from me (`peter-evans`). Looks like you've copied the example and forgotten to edit it.
https://github.com/Maagan-Michael/invitease/blob/dd6a5b71da49051d0d796a26c0bb85c988f62eeb/.github/workflows/pep8-check.yml#L28

**Comment by yarons** [comment]
Sorry, I should have looked further, can I suggest a documentation change for that?
